# ======================================================
# DEVOPS NOTEBOOK — API + MONGODB + REDIS
# ======================================================

services:

  api:
    build: .
    container_name: devops-demo-api
    ports:
      - "5000:5000"
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      mongo:
          condition: service_healthy
      redis: 
          condition: service_healthy

  mongo:
    image: mongo:8
    container_name: devops-demo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:8
    container_name: devops-demo-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


# IMPORTANT: this is outside "services"
volumes:
  mongo_data:

# # ======================================================
# # DEVOPS NOTEBOOK — DOCKER COMPOSE
# # ======================================================

# services:

#   api:
#     build: .
#     container_name: devops-demo-api
#     ports:
#       - "5000:5000"
#     environment:
#       PORT: 5000
#       NODE_ENV: development